version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    container_name: backend_service
    env_file:
      - ../backend/.env.production  # Specify the path to your .env file
    ports:
      - "5100:5100"
    depends_on:
      - db

  frontend:
    build:
      context: ../
      dockerfile: frontend/Dockerfile
    container_name: frontend_service
    env_file:
      - ../frontend/.env.production # Specify the path to your .env file
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - ../backend/.env.production  # Specify the path to your .env file
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/var/mysql/:/var/lib/mysql
